service: roller-coaster-database # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs10.x

stage: dev
region: eu-north-1

functions:
  random:
    handler: handler.random
    events:
      - http:
          path: /random
          method: get

  latest:
    handler: handler.latest
    events:
      - http:
          path: /latest
          method: get

  videos:
    handler: handler.videos
    events:
      - http:
          path: /videos
          method: get

  search:
    handler: handler.search
    events:
      - http:
          path: /search
          method: get

  ride:
    handler: handler.ride
    events:
      - http:
          path: /ride/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

  park:
    handler: handler.park
    events:
      - http:
          path: /park/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

plugins:
  - serverless-offline
